language: objective-c
env:
  matrix:
    - FORMULA_VERSION=
    - FORMULA_VERSION=--HEAD
before_install:
  - brew update
  - brew --env
  - brew config
install:
  - mkdir -p $(brew --repo)/Library/Taps/neovim
  - ln -s $TRAVIS_BUILD_DIR $(brew --repo)/Library/Taps/neovim/homebrew-neovim
script:
  - brew install neovim $FORMULA_VERSION --verbose
  - brew audit neovim --strict
  - brew test neovim
  - nvim --version
matrix:
  fast_finish: true
